### PR TITLE
Rearragements and adjustments

### PR DESCRIPTION
**Pull request by VGSS6102**
**This update:** 
- Changes the name of folder `presets` to `data` 
- Also added `-rpc` to `valorant` and `league-of-legends` folders
- Moves assets of `valorant` and `l-o-l` to separate `assets` folder
- Moves primary files from `presets\valorant\src\content\packed` to just `data\packed`
- Changes `unpack.bat` `config.yml `and other files in the way to correspond to the new changes in names and locations 
- Small fixes

**Why?**
- More logical names and locations of files
   - There's no only presets but other data in `presets` folder, so its `data` folder now
   - Files that being unpacked into the main folder using `unpack.bat` are not related to `valorant-rpc` and their location was not logical 
   
I have tested and it seems to work completely fine after those changes

### CODE REVIEW

**Comment by Purple-Palm** [comment]
I'm not happy with your recent actions regarding the Universal Discord Rich Presence project. Your decision to make changes without prior communication or any form of discussion is not good. 

1. You decided to work on a new branch and make substantial changes without even informing me. This is a collaborative project, and such behavior shows a disregard for teamwork and mutual respect.

2. Changing the folder name from presets to data is not just unnecessary but also confusing. Your justification that "there's no only presets but other data" is baseless. The original structure was clear and intuitive.

3. Moving the assets of valorant and league-of-legends to a separate assets folder is an illogical move. These assets are closely tied to their respective applications, and separating them only makes the directory structure more convoluted.

4. Moving primary files from presets\valorant\src\content\packed to data\packed is another unnecessary change. Your reasoning that their previous location was "not logical" is unfounded. The original structure was clear and functional, the original structure was made to prepare it for further work on it and to unpack the files properly. Again, a team project should have proper communication, if you were communicating in the project properly you would have known this beforehand.

5. Your so-called "small fixes" lack transparency. What exactly did you fix? Without proper communication or explanation, these changes are suspect and could potentially introduce new issues.

Your actions demonstrate a significant lack of respect for the collaborative nature of this project. If you want to contribute, communicate effectively, and justify your changes with valid reasoning.

**Comment by VGSS6102** [comment]
1. No comment

2. Ok

3. Those just unused files that take additional space. They were moved up there to easily ignore them during the update and easy access to them from the top of the structure. Why would it make structure convoluted when all unused files are in one place (stored in separate folders inside of assets folder)

4. Why would structure be clean while primary files are located in the deepest unrelated corner inside of a valorant-rpc project which is only meant to launch advanced rpc for valorant.

5. Small fixes are displayed right below my comment where you can click and see the changes I made. This page is dedicated for this.

image
image

**Comment by Purple-Palm** [comment]
Moving garbage from one folder to another, misleading and creating more garbage? It's illogical.

As I mentioned earlier, it makes sense, but for lack of respect in this collaborative project, you know nothing.

By your action, you've made me stress out and back up the project. Either we fix the potential failure in our collaborative projects, or we don't do anything together anymore.

**Comment by VGSS6102** [comment]
alr lets fix it

**Pull request closed without merging**
